#pragma once

#define MASTER_LEFT

#ifdef RGBLIGHT_ENABLE
#    define RGBLIGHT_ANIMATIONS
#    define RGBLIGHT_HUE_STEP  8
#    define RGBLIGHT_SAT_STEP  8
#    define RGBLIGHT_VAL_STEP  8
#    define RGBLIGHT_LIMIT_VAL 150
#endif

#define TAPPING_TERM 190
#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 1500

#define MOUSEKEY_MAX_SPEED 5
#define MOUSEKEY_DELAY 10
#define MOUSEKEY_INTERVAL 16

#define OLED_DISPLAY_128X64

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
/* #define BOTH_SHIFTS_TURNS_ON_CAPS_WORD */
